### ISSUE TITLE
Registration page

### ISSUE THREAD

**Issue by JedLJRobertson** [SE701ProjectGroup4/Flatmate-Management-System#101]
**User story**
As a user, I should be able to sign up using the frontend by entering my details.

**Acceptance criteria**
- [ ] Password validation (confirm password)
- [ ] User can sign up with UI
- [ ] Link from Homepage
- [ ] Small link from login page (as per hifi)

**Additional context**
Backend work is already done for this, see: #79

**Comment by HongShi10** [comment]
Is this completed?

**Comment by gargi-bansal** [comment]
I think it is? @mitchfaulcon
