### ISSUE TITLE
Add Flat field to User Object

### ISSUE THREAD

**Issue by NathanMills1** [SE701ProjectGroup4/Flatmate-Management-System#104]
**User story**
As a developer, I want the User object that is retrieved from the database to contain a reference to the users flat in order to easily identify and find whether the user is part of a flat, and the other members of that flat

**Acceptance criteria**

- Add Flat field to user object
- Upon retrieving user object from the database, it will contain reference to the users flat.

**Comment by ZianYangAng** [comment]
Reopening issue to add FlatId to user model as well.
