### ISSUE TITLE
Add project license.txt

### ISSUE THREAD

**Issue by jhsi517** [SE701ProjectGroup4/Flatmate-Management-System#11]
Current candidates for licenses:

- MIT
- Creative Commons Attribution 4.0 International Public License

**Comment by Richardng12** [comment]
Please specify why we need a project license in the form of a user story. 
I have recreated this in another issue.

**Comment by jhsi517** [comment]
Haha, yea just saw your one. I will close this one and post my stuff in your one instead :)
