### ISSUE TITLE
Use user ID instead username as the key for the JWT token

### ISSUE THREAD

**Issue by JedLJRobertson** [SE701ProjectGroup4/Flatmate-Management-System#116]
**What is being refactored**
- JWT token production, and use cases

**Describe the change to be made**
When the JWT implementation was done, usernames where the database key, so the JWT includes a claim for a specific username. Now we use IDs for a key, so the claim should be for a ID.

- The JWT generation code needs to be changed
- Anywhere in the code that uses the JWT claim field (e.g. endpoints using auth) should be changed.
- The **wiki page on JWT auth** has a code sample which will need to be updated to get the user by ID, not Username.

**Why is this happening**
The Data Model for users was changed, and has resulted in the current method of giving users being incorrect.

**Comment by Richardng12** [comment]
Closed in PR #131
