### ISSUE TITLE
Create software license

### ISSUE THREAD

**Issue by Richardng12** [SE701ProjectGroup4/Flatmate-Management-System#12]
As a software developer i want to choose a software license to moderate rights towards my code

Acceptance Criteria:

- Research appropriate license
- Create software license on repository

**Comment by jhsi517** [comment]
These are some candidates for the license. 
- MIT
- Creative Commons Attribution 4.0 International Public License

Reason being that some of the documents have sourced information from project that uses those two licenses. See https://www.slant.co/versus/3575/3578/~mit-license_vs_creative-commons for the differences. Essentially the same but the CC one have more restrictions.
