### ISSUE TITLE
Adding additional descriptors to swagger

### ISSUE THREAD

**Issue by Richardng12** [SE701ProjectGroup4/Flatmate-Management-System#128]
**User story**
As a developer, i want extra API documentation on the swagger, so that i can have all the information i need to work with the API in one place, without referring to other sources.

**Acceptance criteria**
- Add additional descriptions to every api endpoint on swagger
- Document fields in controller
- Apply xml file to swagger generator

**Additional context**

**Comment by HongShi10** [comment]
Need to add Header field in Swagger to enable authenticated requests to the web api for testing

**Acceptance criteria**
- Have a header field in Swagger UI that enables authorisation

**Additional context**
Documentation needed as well
