### ISSUE TITLE
Update the user entity - data model in the wiki page

### ISSUE THREAD

**Issue by jhsi517** [SE701ProjectGroup4/Flatmate-Management-System#174]
**Describe the change**
What part of the documentation should change
Update the user entity in the [data model](https://github.com/SE701ProjectGroup4/Flatmate-Management-System/wiki/Data-Models) in the wiki page to reflect the changes made in user model.

**Why is this happening**
Briefly mention why the change is happening if not inherently obvious
Two more fields are added: 
- ResetToken
- CanReset.

Both of which are for checking if the user is authorized to reset password.

**Comment by HongShi10** [comment]
Closing issue as completed  [data model](https://github.com/SE701ProjectGroup4/Flatmate-Management-System/wiki/Data-Models)

**Comment by jhsi517** [comment]
Thanks Hong :)
