### ISSUE TITLE
Support JWT authorization and provide endpoint for tokens

### ISSUE THREAD

**Issue by JedLJRobertson** [SE701ProjectGroup4/Flatmate-Management-System#22]
**User story**
The frontend should be able to request a JWT user token from the backend with appropriate login details.

As a developer, I should be able to specify an API endpoint that requires authorisation and see which user is making the request. 

**Acceptance criteria**
Login endpoint processes correct user credentials and returns JWT token.

JWT token can be used to access authorised endpoints.

**Comment by jhsi517** [comment]
Have verified that JWT auth is working. Closing this ticket
