### ISSUE TITLE
Create Navigation menu and skeleton of main panel

### ISSUE THREAD

**Issue by NathanMills1** [SE701ProjectGroup4/Flatmate-Management-System#35]
**User story**
As a developer I want a back panel and side navigation bar that form the skeleton of our front-end, allowing other developers to begin working on individual panels of the web app.

**Acceptance criteria**
The Web App should contain a side navigation bar allowing users to swap between 3 different panels for the dashboard, payments page and flat management page. This should enable other developers to begin work on the individual panels.

**Additional context**
LoFi diagram of navigation bar draw below

![navigation](https://user-images.githubusercontent.com/43223968/76283939-cdac6a80-6300-11ea-989f-94a75fc50c5d.png)

**Comment by mitchfaulcon** [comment]
Is the user story section finished?

**Comment by NathanMills1** [comment]
> Is the user story section finished?

Whoops, fixed it now
