### ISSUE TITLE
Create data model for application and document

### ISSUE THREAD

**Issue by JedLJRobertson** [SE701ProjectGroup4/Flatmate-Management-System#4]
We need a data model that describes the entities stored by the application (flats, users, chores, etc). Refer to the features list to find all the entities discussed.

**Comment by Richardng12** [comment]
![Data Model](https://user-images.githubusercontent.com/42757966/76045839-1a233d80-5fc3-11ea-9872-1f2f662d5b4d.jpg)

**Comment by DragonMeme** [comment]
Question: Will there be an authentication requirement to access the database? I noticed that there is a password field on the User class.

**Comment by jhsi517** [comment]
Date mode have been documented. Marking this as done
