### ISSUE TITLE
Create list payment component

### ISSUE THREAD

**Issue by Richardng12** [SE701ProjectGroup4/Flatmate-Management-System#40]
**User story**
As a user i want to see all the flat's payments, so that i can make my payments on time

**Acceptance criteria**
Get a 200 response from api for payments of the flat
Component looks similar to hi-fi prototype

**Additional context**

**Comment by DragonMeme** [comment]
If possible also display paid payment history.

**Comment by HongShi10** [comment]
@DragonMeme  is this issue completed?
