### ISSUE TITLE
Create tests for payments api

### ISSUE THREAD

**Issue by Richardng12** [SE701ProjectGroup4/Flatmate-Management-System#47]
**User story**
As a developer, i want to ensure that there are test cases for the payments api, so if any breaking changes are introduced, we can test that all the functionality is still working

**Acceptance criteria**
Test suite is created that tests all payment endpoints
Test suite is synced with github actions

**Additional context**

**Comment by wryao64** [comment]
Blocked by #45

**Comment by wryao64** [comment]
Need to set-up IMapper mock, then implement test cases

**Comment by HongShi10** [comment]
Need to implement a mock HttpContext as well
