### ISSUE TITLE
Create and document hi-fi designs for application

### ISSUE THREAD

**Issue by gargi-bansal** [SE701ProjectGroup4/Flatmate-Management-System#49]
Hi-fi designs should include layout and colour scheme so that it is easier to implement the UI and so that the application is consistent throughout all its pages/screens.

**Comment by jhsi517** [comment]
@gargi-bansal can you please confirm if this ticket can be marked to done

**Comment by gargi-bansal** [comment]
Yup, it can be marked as done

**Comment by jhsi517** [comment]
Cool, marking as done and closing ticket :)
