### ISSUE TITLE
Brainstorm and planning chores feature

### ISSUE THREAD

**Issue by jbea599** [SE701ProjectGroup4/Flatmate-Management-System#55]
**Describe the change**
Initial brainstorm and feature mapping for the chores. This includes some initial rough lo-fi designs to then develop

**Why is this happening**
Chores will be one of the deliverables for the project demo, therefore we need an outline of its features and components.

**Comment by maddiebeagley** [comment]
Not sure if I agree that this is a separate issue, this could be more appropriate to include as an acceptance criterion for issue #56.

**Comment by jbea599** [comment]
Yeah looking again I agree, I will edit the other issue and close this one
