### ISSUE TITLE
Lo-fi designs for chores screen

### ISSUE THREAD

**Issue by jbea599** [SE701ProjectGroup4/Flatmate-Management-System#56]
**Describe the change**
We need an initial brainstorm and feature overview for the chores functionality.
Developing on this,  lo-fi designs for the chores screen, outlining the different features and key areas of development should be made.

**Why is this happening**
To give more direction when starting development on the chores tab.

**Success Criteria**
- MVP for chores feature
- Lo-fi designs for chores screen

**Comment by HongShi10** [comment]
Closing issue as its complete
