### ISSUE TITLE
Ability to reset password if forgotten

### ISSUE THREAD

**Issue by jhsi517** [SE701ProjectGroup4/Flatmate-Management-System#59]
**User story**
As a user, I want to be able to reset my credentials when I need to so that I can access my account when I forget my credentials

**Acceptance criteria**
 - User able to reset password after a verification step
 - System able to verify if the user is not malicious 
 - User be able to log in with the new password
 - User not able to log in with the old password

**Additional context**
Blocked by #23.

**Comment by HongShi10** [comment]
Is this completed?

**Comment by gargi-bansal** [comment]
No, it just needs to be linked up to the back-end
