### ISSUE TITLE
Create id fields for schedule and user

### ISSUE THREAD

**Issue by Richardng12** [SE701ProjectGroup4/Flatmate-Management-System#71]
**User story**
 As a Developer, I want to have id's for both user and schedule entities, so that i can easily abstract the relevant entities and methods.

**Acceptance criteria**
- [ ] Create id fields for schedule and user

- [ ] Recreate migration and apply to database

- [ ] Change relevant primary keys for schedule and user

**Additional context**

**Comment by HongShi10** [comment]
Agreed, all entities should have an ID associated with it as the primary key
