### ISSUE TITLE
[BUG]"Sqlite.SqliteException" In data base when running WebApiBackend

### ISSUE THREAD

**Issue by WilbertGui** [SE701ProjectGroup4/Flatmate-Management-System#72]
Detailed exception:
Microsoft.Data.Sqlite.SqliteException:“SQLite Error 1: 'table "Flat" already exists'.”
Error codes: Startup.cs  L 63
**Severity**
Each time

**Environment:**
 - OS: Windows 10
 - Browser :chrome
 

**Possible solution:**
You may not have to reconfigure the database each time you initialize the configuration, so you may need to increase the determination of the database state

**Comment by mitchfaulcon** [comment]
Was this fixed by pulling from the main repo?

**Comment by HongShi10** [comment]
@WilbertGui if it was fixed by syncing your branch with upstream close the issue pls

**Comment by WilbertGui** [comment]
but fixed. thank you.

**Comment by JainalGandhi** [comment]
Fixed by #38
