### ISSUE TITLE
Flesh out the Homepage and MVP features on the wiki

### ISSUE THREAD

**Issue by gargi-bansal** [SE701ProjectGroup4/Flatmate-Management-System#76]
**Describe the change**
Make the wiki more detailed and flesh out some of the ideas a bit more. The features and general information about the Flatmate system need to be elaborated on further.

**Why is this happening**
The wiki is looking a bit bare at the moment and it needs more documentation.

**Comment by jhsi517** [comment]
@gargi-bansal please ensure to follow the general issue structure :)

**Comment by gargi-bansal** [comment]
Fixed it up, sorry :)
