### ISSUE TITLE
Document justification for custom labels

### ISSUE THREAD

**Issue by maddiebeagley** [SE701ProjectGroup4/Flatmate-Management-System#77]
**Describe the change**
As per the assignment brief, a justification for our choice of our custom issue labels should be documented in the team wiki. 

**Why is this happening**
Though our choice of labels are relatively mainstream, a quick justification of why we chose this subset of labels ensures the entire team has a shared understanding of the decision.

**Comment by Richardng12** [comment]
Added section to wiki

**Comment by HongShi10** [comment]
New labels added will need to update documentation

**Comment by Richardng12** [comment]
Added new labels to documentation
