### ISSUE TITLE
Add chores to the data model

### ISSUE THREAD

**Issue by raghavgarg32** [SE701ProjectGroup4/Flatmate-Management-System#85]
**User story**
As a Developer, I want to be able to use chores data models to represent chores, so that chore can be stored in our database.  

**Acceptance criteria**
*Our data model diagram on wiki should represent the chores data model
*There should be a chores model class

**Additional context**
Data model looks something like this:
![image](https://user-images.githubusercontent.com/29315717/76691551-c2ff2600-66b0-11ea-86a2-b23e8050227f.png)

**Comment by HongShi10** [comment]
completed updating the wiki

**Comment by HongShi10** [comment]
Data model class still needs to be created
